# Run with 15 & 60m
indicators = ["Bollinger Bands"]
takeProfit = 1.01 # take profit when price 0.8% bigger than buy price
percentBelowMa = 0.017 # цена на 1.7% ниже чем оранжевая часовая МА (в рассчете на то, что должна к ней вернуться)

[aaat]
USE_HEIKEN = false
lengthMultiplyer = 4 #e.g. 15m and aaat 60m (15 * 4)

[rsi]
interval = 1 #indicator
low = 29
high = 79
persistence = 1

[bbands]
TimePeriod = 20
NbDevUp = 3
NbDevDn = 3
