trailingStop = 300 #just not use it

UNDERVALUE = 0.8

TAKE_PROFIT = 1.2

THRESHOLD = 2.4

TIMEOUT_MINUTES = 1051200 #2 years

#- использовать с 1 днем!
#- в рельной торговли это АККУМУЛЯТИВНАЯ стратегия (DCA)! (просто подкупаем/продаем по сигналам небольшими порциями, сигналы могут приходить каждый день в течение )
#- безубыточная!
# BT этой страты показывает,что просто покупка/продажа дает ~80%/год. См. стратегию MM-DCA - для аккумуляции
