PERCENTAGE_PRICE_DOWN_BEFORE_MONITORING = 0.98 #Down trend before to look for the up trend to buy
PERCENTAGE_TRAILING_BUY = 1.02 #MOve up before to BUY
PERCENTAGE_STOPLOSS = 0.9
PERCENTAGE_TAKE_PROFIT = 1.10
PERCENTAGE_TRAILING_TP = 0.95
